language: node_js
node_js: '12'
dist: xenial
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.12.0'
    - node_js: '12'
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    - stage: Coverage check
      # If this fails during a PR, CI will fail. However when CI fails, codecov
      # does not post any comment. Since codecov comments are nicer than
      # Travis Buddy comments for this, we skip it during PRs. Also this makes
      # PRs checks faster.
      if: type != pull_request
      script: gulp coverage
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: 'htsIMjwnspI19tEE2LPze3dTHzi7AN6OP717WAmR/l+Kdcu9Koijtc24gOu8UUTcWZ/AOwdJU5UcO3yhRkDxbgYuD7G5P0PbJjGbhDrLKvc0qNYsLYkxcuxmfXkwTBzSXQT9U0lMiOs4gEYgrnvKANPyYdu7HNfSJHqvigMbeS1YjMzkLOwfIy+26i4LJksC5/cG4gPu/1HjoE5zcEPkhJ+VJnFBOmeaidrysUuMmG9YppwqcC+GaFv8ZC8ecuocorNlpSIYq9yYjCD6FZfry+WC13eluO9+XlgFAon8+omQAbD21CvGlY7c7Lvx9DdmT1hC4tldo+rosgS5u794w6XD64XxvZfRlT7LfNcI8zpupIXfYL85XkMhbvB6CxKHHZoYJXpSpSBX8MRaiSMSJYAqJrnt75Z4jsE0HXFTBLTh99Q0AZtmR577oAvz6Fvp8zYtXFFpALXiCo6zOJAPPpGUUnW83ykb9aqr1h2lM9DOAt9fmEb0zFO0sAHnpdBfg01GT/xuItr2irSMQP+6HDsdjmwJaJL4CHrLQ0TK447b0lqiIyDu1JokU/Kr0P2incf0EESdSKYEQeZ1NJlXlcrE2lzzO08Eu5qDpDw8fncGnX4RXMRi5BRKRYhyS17jnVhn/ZpdNabaTJ8D1fObNozOXKdR2R6d7DvakgXVKXM='
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
